// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShelterSync.Data;

#nullable disable

namespace ShelterSync.Migrations
{
    [DbContext(typeof(ShelterSyncDbContext))]
    [Migration("20260530200226_AddPetsTable")]
    partial class AddPetsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShelterSync.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdopted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPetOfTheWeek")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Breed = "Golden Retriever",
                            ImagePath = "https://images.dog.ceo/breeds/retriever-golden/n02099601_3004.jpg",
                            IsAdopted = false,
                            IsPetOfTheWeek = true,
                            Name = "Max",
                            Notes = "Friendly and energetic, loves to play fetch. Great with kids!",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Breed = "Siamese",
                            ImagePath = "https://cdn2.thecatapi.com/images/N7rlRo9Zi.jpg",
                            IsAdopted = false,
                            IsPetOfTheWeek = false,
                            Name = "Luna",
                            Notes = "Playful and affectionate. Loves attention and interactive toys.",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 3,
                            Age = 5,
                            Breed = "Labrador Mix",
                            ImagePath = "https://images.dog.ceo/breeds/labrador/john_walker_000.jpg",
                            IsAdopted = false,
                            IsPetOfTheWeek = false,
                            Name = "Charlie",
                            Notes = "Calm and gentle companion. Perfect for families looking for a loyal friend.",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 4,
                            Age = 1,
                            Breed = "Tabby",
                            ImagePath = "https://cdn2.thecatapi.com/images/b6yBY91Pg.jpg",
                            IsAdopted = false,
                            IsPetOfTheWeek = false,
                            Name = "Whiskers",
                            Notes = "Young and curious kitten. Still learning about the world around her.",
                            Species = "Cat"
                        },
                        new
                        {
                            Id = 5,
                            Age = 4,
                            Breed = "Beagle",
                            ImagePath = "https://images.dog.ceo/breeds/beagle/puppy-1.jpg",
                            IsAdopted = false,
                            IsPetOfTheWeek = false,
                            Name = "Buddy",
                            Notes = "Sweet-natured and food-motivated. Great for training and outdoor adventures.",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 6,
                            Age = 3,
                            Breed = "Persian",
                            ImagePath = "https://cdn2.thecatapi.com/images/c0f_dBlPH.jpg",
                            IsAdopted = false,
                            IsPetOfTheWeek = false,
                            Name = "Mittens",
                            Notes = "Elegant and serene. Prefers a quiet environment with lots of petting.",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
